### ISSUE TITLE
Support for tabs

### ISSUE THREAD

**Issue by jasonvarga** [Konafets/statamic-blueprint-validation#1]
In Statamic 4, blueprints were updated a little. PHPStorm users (and probably other editors using this schema) are now seeing validation errors.

![CleanShot 2023-07-24 at 14 58 18](https://github.com/Konafets/statamic-blueprint-validation/assets/105211/8f99a7a9-6453-4dd6-875d-79a939623c1f)

Blueprints can have a top level `tabs` key. The tabs are keyed by handle.

Each tab has multiple `sections`, which do not have named keys.

```yaml
title: My Blueprint
tabs:
  tab_one:
    display: Tab One
    sections:
      -
        display: My Section # optional
        instructions: Some instructions #optional
        fields: [] # Same as existing fields.
      -
        fields: []
```

The top level `sections` as used on Statamic 3.x is still valid.

If I can help, let me know. But I'm sure you can update this more easily than me.
